# Generated by Django 4.0.3 on 2023-06-22 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webappaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='log',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
